services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartnx_test
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
#   mongodb:
#     image: mongo:5
#     ports:
#       - '27017:27017'
#     volumes:
#       - mongo_data:/data/db

#   api:
#     build: .
#     ports:
#       - '3000:3000'
#     depends_on:
#       - postgres
#       - mongodb
#     environment:
#       POSTGRES_URL: 'postgres://postgres:senhapostgres@postgres:5432/postgres'
#       MONGO_URL: 'mongodb://mongodb:27017/appdb'
#       JWT_SECRET: 'segredo'

volumes:
  postgres_data:
  # mongo_data:
